"""initial schema

Revision ID: 8ddf7a5296a2
Revises: 383338cb9477
Create Date: 2026-03-08 11:34:13.818225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddf7a5296a2'
down_revision: Union[str, None] = '383338cb9477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_habit_confidence_trigger', table_name='habit_confidence')
    op.create_index(op.f('ix_habit_confidence_repository_name'), 'habit_confidence', ['repository_name'], unique=False)
    op.create_index(op.f('ix_habit_confidence_trigger_category'), 'habit_confidence', ['trigger_category'], unique=False)
    op.create_index(op.f('ix_progress_badges_repository_name'), 'progress_badges', ['repository_name'], unique=False)
    op.drop_index('ix_skill_tree_repo', table_name='skill_tree_progress')
    op.drop_constraint('uq_skill_tree_repo', 'skill_tree_progress', type_='unique')
    op.create_index(op.f('ix_skill_tree_progress_repository_name'), 'skill_tree_progress', ['repository_name'], unique=True)
    op.drop_index('ix_user_xp_progress_repo', table_name='user_xp_progress')
    op.drop_constraint('uq_user_xp_repo', 'user_xp_progress', type_='unique')
    op.create_index(op.f('ix_user_xp_progress_repository_name'), 'user_xp_progress', ['repository_name'], unique=True)
    op.drop_index('ix_vuln_guide_category', table_name='vuln_guide_cache')
    op.create_index(op.f('ix_vuln_guide_cache_category'), 'vuln_guide_cache', ['category'], unique=False)
    op.create_index(op.f('ix_vuln_guide_cache_job_id'), 'vuln_guide_cache', ['job_id'], unique=False)
    op.create_index(op.f('ix_vuln_lifecycle_category'), 'vuln_lifecycle', ['category'], unique=False)
    op.create_index(op.f('ix_vuln_lifecycle_state'), 'vuln_lifecycle', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vuln_lifecycle_state'), table_name='vuln_lifecycle')
    op.drop_index(op.f('ix_vuln_lifecycle_category'), table_name='vuln_lifecycle')
    op.drop_index(op.f('ix_vuln_guide_cache_job_id'), table_name='vuln_guide_cache')
    op.drop_index(op.f('ix_vuln_guide_cache_category'), table_name='vuln_guide_cache')
    op.create_index('ix_vuln_guide_category', 'vuln_guide_cache', ['category'], unique=False)
    op.drop_index(op.f('ix_user_xp_progress_repository_name'), table_name='user_xp_progress')
    op.create_unique_constraint('uq_user_xp_repo', 'user_xp_progress', ['repository_name'])
    op.create_index('ix_user_xp_progress_repo', 'user_xp_progress', ['repository_name'], unique=False)
    op.drop_index(op.f('ix_skill_tree_progress_repository_name'), table_name='skill_tree_progress')
    op.create_unique_constraint('uq_skill_tree_repo', 'skill_tree_progress', ['repository_name'])
    op.create_index('ix_skill_tree_repo', 'skill_tree_progress', ['repository_name'], unique=False)
    op.drop_index(op.f('ix_progress_badges_repository_name'), table_name='progress_badges')
    op.drop_index(op.f('ix_habit_confidence_trigger_category'), table_name='habit_confidence')
    op.drop_index(op.f('ix_habit_confidence_repository_name'), table_name='habit_confidence')
    op.create_index('ix_habit_confidence_trigger', 'habit_confidence', ['trigger_category'], unique=False)
    # ### end Alembic commands ###
