"""initial_schema

Revision ID: ff9eb33c8aea
Revises: 
Create Date: 2026-02-26 04:03:47.720445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff9eb33c8aea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=False)
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('repository_name', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('repo_full_name', sa.String(length=512), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('total_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('info_count', sa.Integer(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_created_at'), 'scan_jobs', ['created_at'], unique=False)
    op.create_index('ix_scan_jobs_status_created', 'scan_jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_scan_jobs_user_id'), 'scan_jobs', ['user_id'], unique=False)
    op.create_table('scan_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('logger_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_logs_job_id', 'scan_logs', ['job_id'], unique=False)
    op.create_index('ix_scan_logs_job_id_level', 'scan_logs', ['job_id', 'level'], unique=False)
    op.create_table('vulnerability_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('vuln_id', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('exploitability_score', sa.Float(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('has_ai_explanation', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vuln_records_job_id', 'vulnerability_records', ['job_id'], unique=False)
    op.create_index('ix_vuln_records_severity', 'vulnerability_records', ['severity'], unique=False)
    op.create_index('ix_vuln_records_source', 'vulnerability_records', ['source'], unique=False)
    op.create_index(op.f('ix_vulnerability_records_severity'), 'vulnerability_records', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_records_severity'), table_name='vulnerability_records')
    op.drop_index('ix_vuln_records_source', table_name='vulnerability_records')
    op.drop_index('ix_vuln_records_severity', table_name='vulnerability_records')
    op.drop_index('ix_vuln_records_job_id', table_name='vulnerability_records')
    op.drop_table('vulnerability_records')
    op.drop_index('ix_scan_logs_job_id_level', table_name='scan_logs')
    op.drop_index('ix_scan_logs_job_id', table_name='scan_logs')
    op.drop_table('scan_logs')
    op.drop_index(op.f('ix_scan_jobs_user_id'), table_name='scan_jobs')
    op.drop_index('ix_scan_jobs_status_created', table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_created_at'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
